server:
  port: 0

spring:
  application:
    name: task-cunsumer

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://140.134.26.71:50608/eureka/